# Setup
title: Jiaxu Wu
description: Jiaxu Wu's personal blogs
url: https://jiaxuwu.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<span id="busuanzi_value_page_pv">you are the <i class="fa fa-spinner fa-spin"></i>visitor</span>

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

# Optimize Jekyl SEO Tag
twitter:
  username: Jiaxuw-plant
  card: summary
logo: logo.png
social:
  name: Jiaxu Wu
  links:
    - https://twitter.com/JiaxuWu6
    - https://github.com/jiaxuwu
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-8XGY8ZYGLP

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Jiaxu Wu
  url: https://github.com/jiaxuwu
  email: jiwu08@ulaval.ca
